name = 'aiken-lang/subscriptor'
version = '0.0.0'
license = 'Apache-2.0'
description = "Smart contract wallet supporting pull-based subscriptions"

[repository]
user = 'aiken-lang'
project = 'subscriptor'
platform = 'github'

[[dependencies]]
name = 'aiken-lang/stdlib'
version = '2.1.0'
source = 'github'
